baseURL = "https://bruno.codes/"
title = "Bruno Henrique Paiva"

[params.social]
email = "me@bruno.codes"
github = "brunohpaiva"
linkedin = "brunohpaiva"
mastodon = "https://androiddev.social/@bruno"

defaultContentLanguage = "en"

[languages.en]
languageName = "English"
languageCode = "en"
weight = 1

[[languages.en.menu.main]]
url = "/"
name = "Home"
weight = 1

[[languages.en.menu.main]]
url = "/about"
name = "About"
weight = 2

[[languages.en.menu.main]]
url = "/posts"
name = "Posts"
weight = 3

[[languages.en.menu.main]]
url = "/contact"
name = "Contact"
weight = 4

[languages.pt-br]
languageName = "Português (Brasil)"
languageCode = "pt-BR"
weight = 2

[[languages.pt-br.menu.main]]
url = "/"
name = "Início"
weight = 1

[[languages.pt-br.menu.main]]
url = "/sobre"
name = "Sobre"
weight = 2

[[languages.pt-br.menu.main]]
url = "/posts"
name = "Posts"
weight = 3

[[languages.pt-br.menu.main]]
url = "/contato"
name = "Contato"
weight = 4
